### PR TITLE
Condense HTML whitespace _after_ unquoting attributes

### PR DESCRIPTION
**Pull request by kernc**
... to avoid double spaces everywhere.

### CODE REVIEW

**Comment by kernc** [comment]
@juancarlospaco I'm sorry, did you close because the issue/fix was lacking context? I see I did a very poor documentation job there. :sweat_smile:

The issue is this, e.g.:
```html
<meta content=Pelican  name=generator />
```
Since single-word attributes get unquoted _after_ whitespace is condensed, some double spaces remain, as above.

This simple fix was to avoid that.

**Comment by juancarlospaco** [comment]
I moved to coding using http://nim-lang.org
for Python, for the browser, for backend, for frontend, for general purpose.
It is kinda new, but feels like the Python of the future, allowed me to create things that I can not with Python.

**Comment by kernc** [comment]
Ok ... But this is a widely used [package](https://pypi.org/project/css-html-js-minify/) with many known [dependents](https://libraries.io/pypi/css-html-js-minify/dependents) (unlisted is also Python Pelican/plugins). Closing the shop and shutting the lights like that seems somewhat irresponsible, if I may say so.

Would you consider passing on the maintenance? I can't promise much other than a healthy interest in seeing the things I depend on remain being useful ...

Nim might as well be the next big thing, but Python, rest assured, is not disappearing anywhere fast. :smiley:

**Comment by juancarlospaco** [comment]
I dont understand what are you talking about, I code everyday, you can check my profile I do lots of things,
I just changed from Cython to Nim, everything will be rewritten to Nim eventually, usable from Python too.

**Comment by kernc** [comment]
I certainly did. :nerd_face: Apologies; I'm just trying to ensure this package continues to remain usable as opposed to abandoned. I suppose, the two PRs you had recently closed (#78 and #80) feature important logical fixes that remain relevant even if you _eventually_ rewrite the whole package in Nim. Is that not the case?

**Pull request closed without merging**
