### PR TITLE
Compatibility with CSS like languages

### PR DESCRIPTION
**Pull request by Bluscream**
Like QSS for example.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Thank you very much :exclamation: This is awesome :exclamation: :smile_cat:

**Comment by Bluscream** [comment]
<details>Screenshot</details>

**Comment by Bluscream** [comment]
@juancarlospaco did something bad happen to my changes? I freshly installed it from PIP and my new argument isn't working :/

**Comment by juancarlospaco** [comment]
I think its not on pypi yet.
You can install from GitHub using PIP.

**Comment by Bluscream** [comment]
Why iant it on pipy?

**Comment by juancarlospaco** [comment]
Theres a Windows-only bug that needs to be checked and corrected.
https://github.com/juancarlospaco/anglerfish/issues/24#issue-221762996
Probably next month will do...

**Pull request merged**
